[package]
name = "mission"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "25.0.1"
serde = {version ="1.0.210", features = ["derive"]}
salvo = "0.72"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
connection = { path = "../connection" }